version: '3.8'
services:
  app:
    build: .
    container_name: organization_test_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - organization
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=organization
      - DB_PORT=3306
      - DB_DATABASE=organization
      - DB_USERNAME=root
      - DB_PASSWORD=root

  organization:
    image: mysql:8.0
    container_name: organization
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organization
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
